### ISSUE TITLE
Agent always try to pull docker image when repository prefix is given

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-agent#105]
## Description

Agent always try to pull docker image when repository prefix is given.

## Example

Continuous image pulling.
`
{"timestamp": "2019-02-08T09:38:22.198070Z", "level": "WARNING", "name": "ai.backend.agent.server", "processName": "MainProcess", "message": "could not attach volume (volume not found) to a kernel using language deeplearning-samples "}
{"timestamp": "2019-02-08T09:38:22.199580Z", "level": "INFO", "name": "ai.backend.agent.server", "processName": "MainProcess", "message": "pulling image index.docker.io/lablup/ngc-digits:18.12-tensorflow from registry"}
{"timestamp": "2019-02-08T09:38:24.921130Z", "level": "ERROR", "name": "ai.backend.agent.server", "processName": "MainProcess", "message": "unexpected error", "exc_info": "Traceback (most recent call last):\n  File \"/home/devops/backend.ai/scripts/backend.ai-dev/agent/src/ai/backend/agent/server.py\", line 586, in handle_rpc_exception\n    yield\n  File \"/home/devops/backend.ai/scripts/backend.ai-dev/agent/src/ai/backend/agent/server.py\", line 609, in create_kernel\n    return await self._create_kernel(kernel_id, config)\n  File \"/home/devops/backend.ai/scripts/backend.ai-dev/agent/src/ai/backend/agent/server.py\", line 855, in _create_kernel\n    computer_set.alloc_map.allocate(device_specific_slots)\n  File \"/home/devops/backend.ai/scripts/backend.ai-dev/agent/src/ai/backend/agent/resources.py\", line 299, in allocate\n    'DiscretePropertyAllocMap: insufficient allocatable amount!')\nai.backend.agent.resources.InsufficientResource: DiscretePropertyAllocMap: insufficient allocatable amount!"}
{"timestamp": "2019-02-08T09:39:09.100893Z", "level": "WARNING", "name": "ai.backend.agent.server", "processName": "MainProcess", "message": "could not attach volume (volume not found) to a kernel using language deeplearning-samples "}
{"timestamp": "2019-02-08T09:39:09.102428Z", "level": "INFO", "name": "ai.backend.agent.server", "processName": "MainProcess", "message": "pulling image index.docker.io/lablup/ngc-tensorflow:18.12-py3 from registry"}
`

## Reason

Docker image list does not contain repository information (or, we do not use it on manager/agent) Therefore agent try to pull the image even if it exists.

**Comment by achimnol** [comment]
This is now fixed.
