### ISSUE TITLE
Jupyter Terminal stops responding after ~1 min of no input

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-agent#129]
Steps to reproduce:

* Create a session.
* Launch Jupyter Terminal.
* Wait over 1 min.
* Try to type in the terminal window => no response.

**Comment by achimnol** [comment]
Now resolved. Feel free to reopen if somebody encounters this issue again.

**Comment by achimnol** [comment]
For the record: 1babb44ab55740c023350f468b72e31c4697a6e9 fixes too short recommended netfilter connection tracker (NAT in Linux) timeout which affetcted this issue as well.
