### ISSUE TITLE
Running container is not terminated after idle_timeout

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-agent#139]
I set `idle_timeout = 10`. There is only one `keypair_resource_policy` (`default`).
![image](https://user-images.githubusercontent.com/7539358/64071608-b6892200-ccb8-11e9-9fd9-56a19bbd606f.png)

I created a container in console app, and did not use the container. But, even after ~3 min, the container is not garbage collected. Is this a bug or are there other factors that is related to the container garbage collection?
![image](https://user-images.githubusercontent.com/7539358/64071618-ff40db00-ccb8-11e9-894a-757e4fef1369.png)

**Comment by achimnol** [comment]
Fixed by bd2329d and 784a8103.
